[package]
name = "auto-sort"
version = "0.1.0"
edition = "2021"
github = "lowpolycat1"
authors = [""]
description = ""
license_file = "./license.txt"
repository = "https://github.com/lowpolycat1/auto-sort"
twitter_handle = ""
linkedin_username = ""

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-appender = "0.2.3"
dirs = { version = "5.0.1" }
thiserror = { version = "2.0.9" }
